[package]
name = "gode-check"
version = "1.1.1"
edition = "2024"

[dependencies]
colored = "3.0.0"
reqwest = { version = "0.12.23", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0.145"
sha256 = "1.6.0"
zip = "5.1.1"
