[package]
name = "gode-check"
version = "1.0.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
reqwest = { version = "0.12.12", features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0.137"
sha256 = "1.5.0"
zip-extract = "0.2.1"
