[package]
name = "gode-check"
version = "1.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
reqwest = { version = "0.12.22", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0.140"
sha256 = "1.6.0"
zip-extract = "0.4.0"
